version: '3'
services:
    mariadb:
        build: services/mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mariadb
            MYSQL_USER: mariadb
            MYSQL_PASSWORD: mariadb
    mongo:
        build: services/mongo
        ports:
             - "27017:27017"
    nginx:
        build: services/nginx
        ports:
            - "80:80"
        depends_on:
            - php5
            - php7
        volumes:
            - ./workspace:/var/www
            - ./workspace/logs/nginx:/var/log/nginx
    node:
        build: services/node
        volumes:
            - ./workspace:/var/www
    php5:
        build: services/php5
        volumes:
            - ./workspace:/var/www
    php7:
        build: services/php7
        volumes:
            - ./workspace:/var/www
    redis:
        build: services/redis
        ports:
            - "6379:6379"